---

- name: dpkg | divert files
  command: dpkg-divert --local --divert '{{ item.diverted | default(item.original + diverted_files_default_suffix) }}' --rename '{{ item.original }}'
  args:
    creates: '{{ item.diverted | default(item.original + diverted_files_default_suffix) }}'
  when: (
          (item.state is string and item.state == 'present') or
          item.state is undefined
        )
  with_items: divert_files_list_combined

- name: dpkg | Copy diverted configuration file to original location
  command: cp '{{ item.diverted | default(item.original + diverted_files_default_suffix) }}' '{{ item.original }}'
  args:
    creates: '{{ item.original }}'
  when: (
          (
            (item.state is string and item.state == 'present') or
            item.state is undefined
          ) and item.copy is defined and item.copy == true
        )
  with_items: divert_files_list_combined

- name: dpkg | remove file divert
  file:
    path: '{{ item.original }}'
    state: 'absent'
  when: (
          item.state is string and item.state == 'absent' and
          item.force is defined and item.force
        )
  with_items: divert_files_list_combined

- name: dpkg | remove file divert
  command: dpkg-divert --rename --remove '{{ item.original }}'
  when: (item.state is string and item.state == 'absent')
  with_items: divert_files_list_combined
