---

- name: Test for supported package managers
  assert:
    that: ansible_pkg_mgr in [
            'apt',
          ]

- name: Combine divert file lists
  set_fact:
    divert_files_list_combined: '{{ (
      (divert_files_list|default([])) +
      (divert_files_group_list|default([])) +
      (divert_files_host_list|default([])) ) | unique }}'

- include: dpkg.yml
  when: ansible_pkg_mgr == 'apt'
